name: wethree_flutter_core
description: "A new Flutter package project."
version: 0.1.0
homepage: https://bitbucket.org/we3manager/wethree_flutter_core/src

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"
  

dependencies:
  flutter:
    sdk: flutter
  flare_flutter: ^3.0.2
  flutter_spinkit: ^5.2.1
  global_configuration: ^2.0.0
  flutter_secure_storage: ^9.0.0
  fluttertoast: ^8.2.5
  dio: ^5.4.3+1
  http: ^1.2.1
  datetime_picker_formfield: ^2.0.0
  intl: ^0.18.0
  animations: ^2.0.1
  rive: ^0.13.1
  html2md: ^1.2.5
  infinite_scroll_pagination: ^4.0.0
  flutter_riverpod: ^2.5.1
  dropdown_search: ^5.0.2
  api_cache_manager: ^1.0.2
  multi_select_flutter: ^4.1.2
  internet_connection_checker: ^1.0.0+1
  reactive_forms: ^16.1.1
  reactive_dropdown_search: ^3.0.0
  reactive_date_time_picker: ^3.0.0  
  flutter_hooks: ^0.20.5
  camera: ^0.10.5+9
  geolocator: ^11.0.0
  signature: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - packages/wethree_flutter_core/assets/empty_not_found_404.flr
    - packages/wethree_flutter_core/assets/documents.riv
    - packages/wethree_flutter_core/assets/loader.riv